export const SET_STATE_OBJECTS = "SET_STATE_OBJECTS";
export const CHANGE_OBJECT_LOADER = "CHANGE_OBJECT_LOADER";
export const ERROR_OBJECT_USERS = "ERROR_OBJECT_USERS";
export const SET_CURRENT_OBJECT = "SET_CURRENT_OBJECT";
export const CHANGE_RATE = "CHANGE_RATE";
export const SET_SORT_OBJECTS = "SET_SORT_OBJECTS";
export const SET_LIKED_OBJECTS = 'SET_LIKED_OBJECTS'
